### ISSUE TITLE
Attrs dependency isue

### ISSUE THREAD

**Issue by SteveDoyle2** [imankulov/coverage-plot#6]
With the latest version of coverage, attrs >= 22.2.0 is required.  

coverage-plot is failing with that.

Is there a plan to support the latest version?

**Comment by imankulov** [comment]
Hey Steve! Thanks for the report. There is no specific reason to pin the attrs dependency to its current version. I will update the dependencies in the upcoming days.

**Comment by imankulov** [comment]
Hey Steve! I updated the dependencies and released the new version 0.3.0 to [PyPI](https://pypi.org/project/coverage-plot/0.3.0/). Thanks for the report!

Any questions, please let me know.

**Comment by SteveDoyle2** [comment]
Thank you Roman!  Very much appreciated!  I had to add faker to my
dependencies, but it works!

Thanks again

**Comment by imankulov** [comment]
Thanks for mentioning the issue with faker. It's not needed actually. I released a [new version 0.3.2](https://pypi.org/project/coverage-plot/0.3.2/) that addresses it.
